const UserTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_ERRORS: "SIGN_UP_ERRORS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  FORGOT_PASSWORD_ERROR: "FORGOT_PASSWORD_ERROR",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
};

export default UserTypes;
